name: rate_my_app
description: Allows to kindly ask users to rate your app if custom conditions are met (eg. install time, number of launches, etc...).
version: 1.1.1+1 # Remember to also change the version in "ios/rate_my_app.podspec" and "android/build.gradle".
homepage: https://github.com/Skyost/RateMyApp

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  shared_preferences: '>=2.0.0 <3.0.0'
  flutter_rating_bar: '>=4.0.0 <5.0.0'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.rate_my_app
        pluginClass: RateMyAppPlugin
      ios:
        pluginClass: RateMyAppPlugin
